[options]
  automatic_update = true

  colorscheme = "onedark"
  colorscheme_bg = "dark"

  enable_guicolors = true
  statusline_separator = "arrow"
  statusline_inactive_separator = "arrow"
  buffer_index_type = 4
  enable_tabline_filetype_icon = true
  enable_statusline_mode = false

  clipboard = 'unnamedplus'
  vimcompatible = true
  relativenumber = false
  disabled_plugins = ["neomake.vim"]
  bootstrap_after = "myspacevim#after"


[[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "smart"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  name = "colorscheme"

[[layers]]
  name = "git"

[[layers]]
  name = "github"

[[layers]]
  name = "sudo"

[[layers]]
  name = "lang#python"

[[layers]]
  name = "lang#dart"

[[layers]]
  name = "lang#dockerfile"

[[layers]]
  name = "lang#vim"
