# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/e72d3b8b-21f6-4c6b-8d34-d8c81058c11f";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-fcad8b10-4e2c-4c06-a569-8c173f8bfe96".device = "/dev/disk/by-uuid/fcad8b10-4e2c-4c06-a569-8c173f8bfe96";

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/2B82-40B3";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home/radeox/Vault" = {
    device = "/dev/disk/by-uuid/380A89A23839E500";
    fsType = "ntfs";
    options = [ "uid=1000" "gid=100" "dmask=022" "fmask=113" "umask=0022" ];
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/7d4d0b1f-fcc1-441e-bea2-b65034dccd38"; }];

  # Enables DHCP on each ethernet and wireless interface
  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
