# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.kernelParams = [ "module_blacklist=amdgpu" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/fd3ffffc-3351-4d71-b811-243655e983a2";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-7f78ada2-9e04-474f-8ca8-d7f33438dd58".device =
    "/dev/disk/by-uuid/7f78ada2-9e04-474f-8ca8-d7f33438dd58";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/4859-14ED";
    fsType = "vfat";
  };

  fileSystems."/home/radeox/Storage" = {
    device = "/dev/disk/by-uuid/5BD22DF07CA8F1DA";
    fsType = "ntfs";
    options = [ "uid=1000" "gid=100" "dmask=022" "fmask=113" "umask=0022" ];
  };

  fileSystems."/home/radeox/Vault" = {
    device = "/dev/disk/by-uuid/4E3A2F9E4FF50795";
    fsType = "ntfs";
    options = [ "uid=1000" "gid=100" "dmask=022" "fmask=113" "umask=0022" ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
